default: &default
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  host: banco-staging_db
  pool: 2
  timeout: 5000
  #  password: palantir
production:
  <<: *default
  database: <%= ENV['POSTGRES_NAME']%>
  username: <%= ENV['POSTGRES_USER']%>
  password: <%= ENV['POSTGRES_PASSWORD']%>
development:
  <<: *default
  database: <%= ENV['POSTGRESDESV_NAME']%>
  username: <%= ENV['POSTGRESDESV_USER']%>
  password: <%= ENV['POSTGRESDESV_PASSWORD']%>
